version: 0.2

phases:
  pre_build:
    commands:
      - echo Obteniendo ID de cuenta de AWS de forma dinámica...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      
      - echo Conectándose a Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
      
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/netcoreapi-repo
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Construyendo la imagen de Docker para la API...
      # El comando docker build ahora corre directo porque el Stage previo ya garantizó la calidad
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Empujando la imagen de Docker a Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo ¡Proceso de empaquetado completado con éxito!